### ISSUE TITLE
Дублирующиеся запросы

### ISSUE THREAD

**Issue by Neirokin** [egal/egal-framework-npm-package#16]
При разработке на Nuxt.js иногда дублируются запросы, т.е.:
1. Нажал на кнопку Publish load, c выбранным типом цены Range/Bid - отправился 1 запрос.
2. Нажал ещё раз (не обновляя страницу или не переходя с неё) - отправилось 2 запроса
3. Нажал ещё раз - отправилось уже 3 запроса. И так до бесконечности
В чём проблема абсолютно не понимаю.
Пытался продебажить и отследить приходящие значения в плагине observer.js (приходил только один результат, не смотря на количество запросов) и в Egal.ts (лисенер вызывался столько раз, сколько и отправлялось запросов). В код фреймворка не лез

**Comment by Yulya-Yu** [comment]
Баг не воспроизводится, запрос закрыт.
