### ISSUE TITLE
Реализовать кастомные фильтры на фронте

### ISSUE THREAD

**Issue by x-alice-x** [egal/egal-framework-npm-package#37]
Нужно доработать фильтры так, чтобы можно было отправлять кастомные фильтры. 
По какому-либо параметру различать кастомный фильтр и фильтр фреймворка. Если это фильтр фреймворка, преобразовывать его для передачи на бэк, а если кастомный - отправлять как есть.
Примеры кастомных фильтров:
```
        [
            "name",
            "EquipmentType",
            {
                "equipment_type": "1000000000000000000000"
            }
        ],

        [
            "name",
            "SpecialEquipmentType",
            {
                "special_equipment_type": "100000000000000000"
            }
        ],

        [
            "name",
            "CertificationSubset",
            {
                "certification": "1000"
            }
        ],
```

**Comment by Yulya-Yu** [comment]
added in new release:
https://github.com/egal/egal-framework-npm-package/releases/tag/v2.0.0-beta31
