### ISSUE TITLE
Интеграция UMRT (User Master Refresh Token) для UMT.

### ISSUE THREAD

**Issue by Yulya-Yu** [egal/egal-framework-npm-package#54]
https://github.com/egal/egal-framework-php-package/issues/39

**Comment by Yulya-Yu** [comment]
Добавлено в релизе:
https://github.com/egal/egal-framework-npm-package/releases/tag/v2.0.0-beta43-react-native

**Comment by rollsover** [comment]
@Yulya-Yu 🚩 2
